name: MoneyPlugin
main: com.yuta.money.MoneyPlugin
version: 1.1.0.0-pre2
api-version: '1.20'
author: yuta25912

commands:
  money:
    description: 自分の所持金を表示します。
    usage: /money
  money_all:
    description: 全プレイヤーの所持金を表示します。(OP専用)
    usage: /money_all
  pay:
    description: 他のプレイヤーにお金を支払います。
    usage: /pay <プレイヤー名> <金額>
  want:
    description: 他のプレイヤーにお金を要求します。
    usage: /want <プレイヤー名> <金額>
  sell:
    description: アイテム売却用のGUIを開きます。
    usage: /sell
  shop:
    description: ショップを開きます。
    usage: /shop
  setmoney:
    description: プレイヤーの所持金を設定します。(OP専用)
    usage: /setmoney <プレイヤー名> <金額>
  pocket:
    description: 共有のPocketチェストを開きます。
    usage: /pocket
  setprices:
    description: アイテムの価格と日本語名を設定します。(OP専用)
    usage: /setprices <アイテムID> <日本語名> <min> <通常価格> <max>
  request:
    description: 運営に要望を送信します。
    usage: /request <要望内容>
  ranking:
    description: 指定した項目のランキングを表示します。
    usage: /ranking <money|playtime>