name: MoneyPlugin
main: com.yuta.money.MoneyPlugin
version: 1.1.0.0-pre1
api-version: '1.20'
money-unit: KP

commands:
  money:
    description: Show your balance
  money_all:
    description: Show balances of all players (OP)
  pay:
    description: Pay money to another player
    usage: /pay <player> <amount>
  want:
    description: Ask money from another player
    usage: /want <player> <amount>
  sell:
    description: Open selling GUI
  shop:
    description: Open shop
  setmoney:
    description: Set player's money (OP)
    usage: /setmoney <player> <amount>
  pocket:
    description: Open shared pocket chest
  setprices:
    description: Set sell price for material (OP)
    usage: /setprices <MATERIAL_ID> <price>